scala_library(
  sources=['ThriftUnixSocket.scala'],
  dependencies=[
    '3rdparty/jvm:ammonite-ops',
    '3rdparty/jvm:junixsocket',
    '3rdparty/jvm:thrift',
  ]
)

scala_library(
  name='feature-test',
  sources=['FeatureTest.scala'],
  dependencies=[
    '3rdparty/jvm:thrift',
  ],
)
